### ISSUE TITLE
File directory issue

### ISSUE THREAD

**Issue by Matsukami7** [JonasBonno/docker-ftb-revelation#3]
Hi! this docker container works amazing! My only issue is, after i run the server, i cannot see the file location when i SFTP into my Linux VM, i try to find it and it doestn seem to show up, 

I'm trying to find a way to pull files from the server (backups and other things) and maybe add in files ( like mods) is there any way to do this? Thanks!

**Comment by JonasBonno** [comment]
Currently the two containers, the server and the data container, only share the world-data folder between them, so to take a backup of the world-data your would run something like this:

**Backup:**
_docker run --rm --volumes-from [name of your data container] -v /[path on host]:/backup alpine tar zcpf /backup/minecraft_world_$(date +%F).tgz /minecraft/world

**Restore:**
_docker stop [name of your container]
docker run --rm --volumes-from [name of your data container] -v /[path on host]:/backup alpine tar zxpf /backup/[name of backup file].tgz
docker start [name of your container]_

If you want to change things in the server container you could use the following to access it:

**Access container:**
_docker exec -it [name of your container] bash_

Inside the container you could install Linux packets or download/modify additional files, but it cannot be done from SFTP, you need SSH/console on host to do this.

**Comment by Matsukami7** [comment]
Thank you for the response, so there is no way that it can run off the host (i found another game server that did this, even made a directory on the host) so i was able to just SFTP in and edit/change files. it just made work easier. If not thats ok, im just learning, and weighing my options.

**Comment by JonasBonno** [comment]
The only option is to skip the data container with:

_docker run --tty=true --interactive=true --detach=true --name=[name of your container] -v /[path on host]:/minecraft/world --publish=[port on your host]:25565 jonasbonno/ftb-revelation_

This will cause the server container to use a local folder for the world-data, but still you cannot add/modify the server mods from SFTP, you need SSH/console on host to do this.

**Comment by Matsukami7** [comment]
Thank you so much for the help! one more thing, is there a way to allow the server to use more ram. or  do i just edit a file in the container?

**Comment by JonasBonno** [comment]
You’re welcome. Yes, you would have to edit the start script within the server container by hand.

**Comment by cronyakatsuki** [comment]
> The only option is to skip the data container with:
> 
> _docker run --tty=true --interactive=true --detach=true --name=[name of your container] -v /[path on host]:/minecraft/world --publish=[port on your host]:25565 jonasbonno/ftb-revelation_
> 
> This will cause the server container to use a local folder for the world-data, but still you cannot add/modify the server mods from SFTP, you need SSH/console on host to do this.

The world won't create when you bind `/minecraft/world` on your system, it will crash.

**Comment by JonasBonno** [comment]
> The world won't create when you bind `/minecraft/world` on your system, it will crash.

Hi @cronyakatsuki,
Make sure that the folder permissions are set currently, that the "minecraft" user inside the containers has read/write permissions on the folder outside the container matching the containers user and group id for the user. I made the container using volumes for this reason because I felt it was a hassel.
