### ISSUE TITLE
Server Fails to Download

### ISSUE THREAD

**Issue by Kesslerb2** [JonasBonno/docker-ftb-revelation#4]
Looks like curseforge changed their API slightly and the `wget` command fails in the Dockerfile.
```        
curl https://media.forgecdn.net/files/2778/975/FTBRevelationServer_3.2.0.zip > FTBRevelationServer_3.2.0.zip && \
```
Solves the problem.

**Comment by JonasBonno** [comment]
Thanks for the heads up. I have now added v3.3.0 and v3.4.0.
If you need a working v3.2.0 you could use "jonasbonno/ftb-revelation:3.2.0" from https://hub.docker.com
