### ISSUE TITLE
log4j vulnerability

### ISSUE THREAD

**Issue by IrishWolf** [JonasBonno/docker-ftb-revelation#8]
Hey,

I've got the 3.4.0-Docker running and tryed to fix the log4j-vulnerability by myself but it didn't work out. :/

**What I did:**
I've downloaded the .xml from the Mojang-site with the fix for the versions [1.12-1.16.5 ](https://launcher.mojang.com/v1/objects/dd2b723346a8dcd48e7f4d245f6bf09e98db9696/log4j2_17-111.xml) and then edited the start.sh and start.bat to the folllowing:
```java -server -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -Xmx6144M -Xms4096M -jar forge-1.12.2-14.23.5.2846-universal.jar -Dlog4j.configurationFile=log4j2_112-116.xml -Dlog4j2.formatMsgNoLookups=true nogui```

After that I restartet the server and postet "${date:YYYY}" in the chat.
The output in the concole and logs was "2021" - so it's still vulnerable.

Can anybody help what I did wrong or how I can fix this?

**Comment by JonasBonno** [comment]
I already added the Mojang recommended mitigation on top of Log4jPatcher provided by the FTB installer.
Are you using latest build? If not please try run the latest build without changing the start.sh file, and all mitigations should already be in place.

Can you confirm the mitigations work with latest build?

**Comment by JonasBonno** [comment]
I just realized that is the version 3.5.0 that listed on [feed-the-beast.com](https://feed-the-beast.com/modpack/ftb_revelation) is still beta and your version is therefore the latest stable release. I am building 3.4.0 with the mitigations now.
