### ISSUE TITLE
Server won't start, Error: Exception in server tick loop

### ISSUE THREAD

**Issue by IrishWolf** [JonasBonno/docker-ftb-revelation#9]
Hello,

my server suddenly won't start.

Before the restart it had some errors in the console caused by a high tickrate/running behind around 1000-4000ms.

Now it won't start with the follwoing error-log: [https://pastebin.com/3WFF4z2V](https://pastebin.com/3WFF4z2V)
The console-log ends with the following (seems to indicate another mod than the crash-report): [https://pastebin.com/hRp3MvkQ](https://pastebin.com/hRp3MvkQ)
I've got literally no idea where to start looking or fixing at^^'

The server itself is a Ubuntu 18.04.6 LTS (everything updated) and the docker is the v3.4.0-log4j.

I hope someone can help me with this problem.

**Comment by IrishWolf** [comment]
Rebuild the server-container and used a backup. Now everything seems to work again (lost the whitelist and ranks tho).

But if the problem can be found it would be great (usually some things come again and again...)

**Comment by JonasBonno** [comment]
My best guess is the file permissions, maybe you mounted the world folder (volume) from the host filesystem and the owner/group or permissions where incorrect set.
